"""
generate_thumbnails_ai.py — AI-powered thumbnails using Pollinations.ai
- Background: generated by Flux AI (via Pollinations free API, commercial use)
- Overlay: bold text + stat + accent bars (Pillow)
- Correct aspect ratios: 1080×1920 Shorts, 1280×720 Long
- No API key required — Pollinations is free & commercial-ready

Usage:
    python3 scripts/generate_thumbnails_ai.py             # all videos
    python3 scripts/generate_thumbnails_ai.py S01117      # single video
"""
import os, sys, requests, time
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageEnhance
from io import BytesIO

BASE = "/Users/ar/Development/projects/FactForge"
POLLINATIONS_URL = "https://image.pollinations.ai/prompt/{prompt}?width={w}&height={h}&nologo=true&model=flux&seed={seed}"


def get_font(size):
    for path in [
        "/System/Library/Fonts/Supplemental/Impact.ttf",
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
    ]:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except:
                pass
    return ImageFont.load_default()


def hex_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


def outline_text(draw, xy, text, font, fill, outline, width=6):
    x, y = xy
    for dx in range(-width, width+1, 2):
        for dy in range(-width, width+1, 2):
            if dx or dy:
                draw.text((x+dx, y+dy), text, font=font, fill=outline, anchor="mm")
    draw.text(xy, text, font=font, fill=fill, anchor="mm")


def fetch_ai_background(prompt, width, height, seed=42, retries=3):
    """Download AI-generated background from Pollinations.ai"""
    url = POLLINATIONS_URL.format(
        prompt=requests.utils.quote(prompt),
        w=width, h=height, seed=seed
    )
    for attempt in range(retries):
        try:
            print(f"    🎨 AI background: {prompt[:50]}...", end=" ", flush=True)
            r = requests.get(url, timeout=60)
            if r.status_code == 200 and len(r.content) > 5000:
                img = Image.open(BytesIO(r.content)).convert("RGB")
                img = img.resize((width, height), Image.Resampling.LANCZOS)
                print(f"✓ ({len(r.content)//1024}KB)")
                return img
            else:
                print(f"retry ({r.status_code})")
        except Exception as e:
            print(f"retry ({e})")
        time.sleep(3)
    print("⚠️ fallback to gradient")
    return None


def make_gradient_bg(W, H, bg_rgb, acc_rgb):
    """Fallback: solid gradient background"""
    img = Image.new("RGB", (W, H))
    draw = ImageDraw.Draw(img)
    for y in range(H):
        t = y / H
        r = int(bg_rgb[0] * (1 - t * 0.35))
        g = int(bg_rgb[1] * (1 - t * 0.35))
        b = int(bg_rgb[2] * (1 - t * 0.35))
        draw.line([(0, y), (W, y)], fill=(r, g, b))
    return img


def make_thumbnail_ai(vid_id, cfg):
    is_short = vid_id.startswith("S")
    W, H = (1080, 1920) if is_short else (1280, 720)

    acc_rgb = hex_rgb(cfg["accent"])
    bg_rgb = hex_rgb(cfg["bg"])

    # ── 1. AI Background (or gradient fallback) ──────────────────────
    ai_prompt = cfg.get("ai_prompt", "")
    img = None
    if ai_prompt:
        img = fetch_ai_background(ai_prompt, W, H, seed=cfg.get("seed", 42))

    if img is None:
        img = make_gradient_bg(W, H, bg_rgb, acc_rgb)

    # ── 2. Dark overlay so text is always readable ────────────────────
    overlay = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    od = ImageDraw.Draw(overlay)
    # Semi-transparent black gradient from bottom (where text lives)
    for y in range(H):
        t = y / H
        # Bottom 60% gets darker overlay
        if t > 0.4:
            alpha = int(180 * ((t - 0.4) / 0.6))
        else:
            alpha = int(60 * (1 - t / 0.4))
        od.line([(0, y), (W, y)], fill=(0, 0, 0, alpha))
    img = Image.alpha_composite(img.convert("RGBA"), overlay).convert("RGB")
    draw = ImageDraw.Draw(img)

    # ── 3. Top accent glow blob ───────────────────────────────────────
    blob = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    bd = ImageDraw.Draw(blob)
    for rad in range(min(W, H) // 2, 0, -30):
        alpha = max(0, int(50 * (1 - rad / (min(W, H) // 2))))
        bd.ellipse([W - rad, -rad, W + rad, rad], fill=(*acc_rgb, alpha))
    img = Image.alpha_composite(img.convert("RGBA"), blob).convert("RGB")
    draw = ImageDraw.Draw(img)

    # ── 4. Bold accent bar at top ─────────────────────────────────────
    bar_h = max(8, int(H * 0.013))
    draw.rectangle([0, 0, W, bar_h], fill=acc_rgb)

    # ── 5. MAIN STAT (hero) ───────────────────────────────────────────
    stat = cfg.get("stat", "")
    if stat:
        stat_size = cfg.get("stat_size", int(H * 0.30))
        stat_y = cfg.get("stat_y", int(H * 0.38))
        f_stat = get_font(stat_size)
        # Glow layers
        for glow_r, alpha in [(stat_size // 2, 30), (stat_size // 3, 50), (stat_size // 4, 70)]:
            glow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
            gd = ImageDraw.Draw(glow)
            gd.text((W // 2, stat_y), stat, font=f_stat, fill=(*acc_rgb, alpha), anchor="mm")
            glow = glow.filter(ImageFilter.GaussianBlur(radius=glow_r))
            img = Image.alpha_composite(img.convert("RGBA"), glow).convert("RGB")
        draw = ImageDraw.Draw(img)
        outline_text(draw, (W // 2, stat_y), stat, f_stat, acc_rgb, (0, 0, 0), width=8)

    # ── 6. Line 1 (white bold) ────────────────────────────────────────
    line1 = cfg.get("line1", "").upper()
    if line1:
        l1_size = cfg.get("l1_size", int(H * 0.075))
        l1_y = cfg.get("l1_y", int(H * 0.65))
        f1 = get_font(l1_size)
        outline_text(draw, (W // 2, l1_y), line1, f1, (255, 255, 255), (0, 0, 0), width=6)

    # ── 7. Line 2 (accent color) ──────────────────────────────────────
    line2 = cfg.get("line2", "").upper()
    if line2:
        l2_size = cfg.get("l2_size", int(H * 0.065))
        l2_y = cfg.get("l2_y", int(H * 0.75))
        f2 = get_font(l2_size)
        outline_text(draw, (W // 2, l2_y), line2, f2, acc_rgb, (0, 0, 0), width=5)

    # ── 8. Category pill ─────────────────────────────────────────────
    cat = cfg.get("category", "").upper()
    if cat:
        f_cat = get_font(int(H * 0.028))
        bbox = draw.textbbox((0, 0), cat, font=f_cat, anchor="mm")
        pw = (bbox[2] - bbox[0]) + int(W * 0.05)
        ph = int(H * 0.045)
        px, py = W // 2, int(H * 0.055)
        draw.rounded_rectangle([px - pw // 2, py - ph // 2, px + pw // 2, py + ph // 2],
                                radius=ph // 2, fill=acc_rgb)
        draw.text((px, py), cat, font=f_cat, fill=(0, 0, 0), anchor="mm")

    # ── 9. FACTFORGE watermark ────────────────────────────────────────
    f_wm = get_font(int(H * 0.022))
    wm_y = H - int(H * 0.025)
    draw.text((W // 2, wm_y), "FACTFORGE", font=f_wm,
              fill=(*acc_rgb, 180), anchor="mm")

    # ── 10. Bottom bar ────────────────────────────────────────────────
    draw.rectangle([0, H - bar_h, W, H], fill=acc_rgb)

    # Save
    out = f"{BASE}/output/{vid_id}/thumbnail.jpg"
    os.makedirs(f"{BASE}/output/{vid_id}", exist_ok=True)
    img.save(out, "JPEG", quality=95)
    size_kb = os.path.getsize(out) // 1024
    print(f"  ✅ {vid_id} ({'Short 1080×1920' if is_short else 'Long 1280×720'}) — {size_kb}KB saved")
    return out


# ═══════════════════════════════════════════════════════════════
# THUMBNAIL CONFIGS WITH AI PROMPTS
# ai_prompt: describe the BACKGROUND scene for Flux to generate
# Keep it cinematic, no text, photorealistic or dramatic illustration
# ═══════════════════════════════════════════════════════════════
THUMBNAILS = {
    # ─── LONG VIDEOS ───────────────────────────────────────────────
    "L00100": {
        "bg": "#1565C0", "accent": "#FFD600",
        "ai_prompt": "billionaire luxury skyscraper penthouse view of New York city at night, dramatic lighting, cinematic, no text",
        "seed": 101,
        "stat": "#1", "stat_size": 380, "stat_y": 310,
        "line1": "Richest person", "l1_size": 72, "l1_y": 530,
        "line2": "on Earth — revealed", "l2_size": 62, "l2_y": 610,
        "category": "Wealth Ranking 2026",
    },
    "L00016": {
        "bg": "#1B5E20", "accent": "#FFEB3B",
        "ai_prompt": "contrast between luxury skyscraper and poverty slum, aerial drone view, dramatic golden hour lighting, cinematic, no text",
        "seed": 16,
        "stat": "45%", "stat_size": 340, "stat_y": 290,
        "line1": "Owned by 1% of people", "l1_size": 66, "l1_y": 510,
        "line2": "Bottom 50% share 2%", "l2_size": 58, "l2_y": 590,
        "category": "The Wealth Gap",
    },

    # ─── SHORTS ────────────────────────────────────────────────────
    "S01117": {
        "bg": "#1A237E", "accent": "#69FF47",
        "ai_prompt": "glowing AI robot typing on a laptop in a futuristic government building, dramatic blue light, cinematic portrait, no text",
        "seed": 1117,
        "stat": "36", "stat_size": 520, "stat_y": 680,
        "line1": "Politicians passed", "l1_size": 94, "l1_y": 1150,
        "line2": "ChatGPT's law", "l2_size": 88, "l2_y": 1270,
        "category": "AI Wrote the Law",
    },
    "S01279": {
        "bg": "#0D47A1", "accent": "#FF3D00",
        "ai_prompt": "DNA double helix glowing in blue laboratory, scientist hands holding CRISPR equipment, dark dramatic, cinematic, no text",
        "seed": 1279,
        "stat": "CRISPR", "stat_size": 240, "stat_y": 650,
        "line1": "Edited babies' DNA", "l1_size": 88, "l1_y": 1120,
        "line2": "Can't be undone", "l2_size": 82, "l2_y": 1240,
        "category": "Gene Editing Scandal",
    },
    "S01062": {
        "bg": "#B71C1C", "accent": "#FFD600",
        "ai_prompt": "close up of EpiPen auto-injector on hospital bed with dollar bills, dramatic red and gold lighting, cinematic, no text",
        "seed": 1062,
        "stat": "$608", "stat_size": 420, "stat_y": 680,
        "line1": "EpiPen costs $7", "l1_size": 90, "l1_y": 1150,
        "line2": "to make", "l2_size": 92, "l2_y": 1270,
        "category": "Healthcare Robbery",
    },
    "S01110": {
        "bg": "#004D40", "accent": "#FFEB3B",
        "ai_prompt": "beautiful German university campus at sunset, students studying, historic European architecture, golden light, cinematic, no text",
        "seed": 1110,
        "stat": "FREE", "stat_size": 440, "stat_y": 680,
        "line1": "University in Germany", "l1_size": 86, "l1_y": 1150,
        "line2": "costs $0", "l2_size": 94, "l2_y": 1270,
        "category": "Free Education",
    },
    "S01155": {
        "bg": "#01579B", "accent": "#00E5FF",
        "ai_prompt": "massive Grand Ethiopian Renaissance Dam aerial view, dramatic cloudy sky, powerful water flow, cinematic, no text",
        "seed": 1155,
        "stat": "6,000MW", "stat_size": 220, "stat_y": 650,
        "line1": "Africa's largest dam", "l1_size": 88, "l1_y": 1120,
        "line2": "changed the Nile", "l2_size": 82, "l2_y": 1240,
        "category": "GERD Dam",
    },
    "S01183": {
        "bg": "#4A148C", "accent": "#76FF03",
        "ai_prompt": "hepatitis C virus cells under microscope glowing purple, dramatic medical science, cinematic, no text",
        "seed": 1183,
        "stat": "95%", "stat_size": 460, "stat_y": 680,
        "line1": "Pill that cures Hep-C", "l1_size": 84, "l1_y": 1150,
        "line2": "nobody can afford", "l2_size": 84, "l2_y": 1270,
        "category": "Drug Pricing Scandal",
    },
    "S01185": {
        "bg": "#212121", "accent": "#FF1744",
        "ai_prompt": "surveillance cameras tracking faces in a crowd, face recognition technology overlay, dark dystopian, cinematic, no text",
        "seed": 1185,
        "stat": "117B", "stat_size": 400, "stat_y": 680,
        "line1": "Photos of your face", "l1_size": 88, "l1_y": 1150,
        "line2": "scraped without consent", "l2_size": 74, "l2_y": 1270,
        "category": "Facial Recognition",
    },
    "S01190": {
        "bg": "#263238", "accent": "#FF6D00",
        "ai_prompt": "OpenAI headquarters building exterior at night, dramatic corporate lighting, blue glow, cinematic, no text",
        "seed": 1190,
        "stat": "→ NFP", "stat_size": 280, "stat_y": 660,
        "line1": "OpenAI is being", "l1_size": 90, "l1_y": 1130,
        "line2": "sold to Wall Street", "l2_size": 82, "l2_y": 1250,
        "category": "OpenAI Controversy",
    },
    "S01215": {
        "bg": "#1A237E", "accent": "#F50057",
        "ai_prompt": "NSA surveillance center aerial view at night, dark government building, spy satellite in sky, dramatic, cinematic, no text",
        "seed": 1215,
        "stat": "193", "stat_size": 480, "stat_y": 680,
        "line1": "Countries spied on", "l1_size": 88, "l1_y": 1150,
        "line2": "by the NSA", "l2_size": 92, "l2_y": 1270,
        "category": "NSA Surveillance",
    },
    "S01224": {
        "bg": "#37474F", "accent": "#FFD600",
        "ai_prompt": "prison factory interior with inmates working machinery, dramatic industrial lighting, dark shadows, cinematic, no text",
        "seed": 1224,
        "stat": "$0.23", "stat_size": 360, "stat_y": 680,
        "line1": "Prisoners work for", "l1_size": 88, "l1_y": 1150,
        "line2": "23 cents per hour", "l2_size": 80, "l2_y": 1270,
        "category": "Prison Labor",
    },
    "S01267": {
        "bg": "#0D0D0D", "accent": "#00E5FF",
        "ai_prompt": "futuristic AI data center servers glowing blue in dark room, AGI robot brain visualization, cinematic, no text",
        "seed": 1267,
        "stat": "AGI", "stat_size": 480, "stat_y": 700,
        "line1": "To build AGI —", "l1_size": 90, "l1_y": 1160,
        "line2": "$500 billion needed", "l2_size": 82, "l2_y": 1280,
        "category": "AGI Race",
    },
    "S01268": {
        "bg": "#311B92", "accent": "#FFEA00",
        "ai_prompt": "Hollywood film set with AI robot director, dramatic studio lights, cinematic behind the scenes, no text",
        "seed": 1268,
        "stat": "AI", "stat_size": 560, "stat_y": 720,
        "line1": "Made this film", "l1_size": 94, "l1_y": 1180,
        "line2": "zero human writers", "l2_size": 82, "l2_y": 1300,
        "category": "AI Film Industry",
    },
    "S00794": {
        "bg": "#0A0A0A", "accent": "#00E5FF",
        "ai_prompt": "race between Google DeepMind and OpenAI headquarters buildings at night, dramatic light beams racing upward, cinematic, no text",
        "seed": 794,
        "stat": "2027?", "stat_size": 360, "stat_y": 680,
        "line1": "Nobody is in charge", "l1_size": 84, "l1_y": 1150,
        "line2": "of the AGI race", "l2_size": 86, "l2_y": 1270,
        "category": "AGI Race",
    },
    "S00925": {
        "bg": "#1B1B1B", "accent": "#FF6F00",
        "ai_prompt": "oil refinery at sunset with thick black smoke, internal corporate documents, dramatic warning red sky, cinematic, no text",
        "seed": 925,
        "stat": "1977", "stat_size": 400, "stat_y": 680,
        "line1": "Exxon knew", "l1_size": 100, "l1_y": 1150,
        "line2": "about climate change", "l2_size": 78, "l2_y": 1270,
        "category": "Exxon Scandal",
    },
    "S01066": {
        "bg": "#1B5E20", "accent": "#FFEA00",
        "ai_prompt": "El Salvador streets transformation from gang violence to peaceful city, dramatic before-after lighting, cinematic, no text",
        "seed": 1066,
        "stat": "95%", "stat_size": 460, "stat_y": 680,
        "line1": "Drop in murders", "l1_size": 94, "l1_y": 1150,
        "line2": "how El Salvador did it", "l2_size": 74, "l2_y": 1270,
        "category": "El Salvador Miracle",
    },
    "S01080": {
        "bg": "#0D0D0D", "accent": "#E040FB",
        "ai_prompt": "futuristic AI microphone cloning human voice with waveform visualization, dark purple neon light, cinematic, no text",
        "seed": 1080,
        "stat": "3 SEC", "stat_size": 340, "stat_y": 670,
        "line1": "AI clones your voice", "l1_size": 86, "l1_y": 1140,
        "line2": "in 3 seconds", "l2_size": 92, "l2_y": 1260,
        "category": "Voice Cloning AI",
    },
    "S01084": {
        "bg": "#B71C1C", "accent": "#FFD600",
        "ai_prompt": "hospital emergency room dramatic lighting with a single aspirin pill close-up and a massive bill invoice, cinematic, no text",
        "seed": 1084,
        "stat": "$40", "stat_size": 500, "stat_y": 700,
        "line1": "For one aspirin", "l1_size": 94, "l1_y": 1170,
        "line2": "at a US hospital", "l2_size": 86, "l2_y": 1290,
        "category": "Healthcare Robbery",
    },
    "S01097": {
        "bg": "#0D0D2B", "accent": "#00E5FF",
        "ai_prompt": "quantum computer glowing blue with padlocks shattering, encryption breaking visualization, dark dramatic, cinematic, no text",
        "seed": 1097,
        "stat": "10YRS", "stat_size": 320, "stat_y": 670,
        "line1": "Until all passwords", "l1_size": 86, "l1_y": 1140,
        "line2": "can be hacked", "l2_size": 90, "l2_y": 1260,
        "category": "Quantum Computing",
    },
    "S01113": {
        "bg": "#1A1A1A", "accent": "#FF3D00",
        "ai_prompt": "rusty corroded water pipes in Flint Michigan with brown contaminated water, dramatic dark documentary style, cinematic, no text",
        "seed": 1113,
        "stat": "100K", "stat_size": 400, "stat_y": 680,
        "line1": "People poisoned", "l1_size": 94, "l1_y": 1150,
        "line2": "by their government", "l2_size": 82, "l2_y": 1270,
        "category": "Flint Water Crisis",
    },
    "S01128": {
        "bg": "#0A0A1A", "accent": "#00FF88",
        "ai_prompt": "Stuxnet computer virus code glowing green destroying nuclear centrifuges in dark server room, cyberwarfare dramatic, cinematic, no text",
        "seed": 1128,
        "stat": "1,000", "stat_size": 380, "stat_y": 680,
        "line1": "Machines destroyed", "l1_size": 90, "l1_y": 1150,
        "line2": "by a computer virus", "l2_size": 80, "l2_y": 1270,
        "category": "Stuxnet Cyberweapon",
    },
    "S01131": {
        "bg": "#1A0A2E", "accent": "#FF1744",
        "ai_prompt": "AI robot publishing fake scientific research papers with fabricated graphs, dramatic red academic laboratory, cinematic, no text",
        "seed": 1131,
        "stat": "1M+", "stat_size": 440, "stat_y": 680,
        "line1": "Fake papers published", "l1_size": 84, "l1_y": 1150,
        "line2": "by AI bots", "l2_size": 94, "l2_y": 1270,
        "category": "AI Science Fraud",
    },
    "S01644": {
        "bg": "#4A2800", "accent": "#FFD700",
        "ai_prompt": "Mansa Musa African emperor gold throne surrounded by mountains of gold, medieval Mali Empire dramatic painting style, cinematic, no text",
        "seed": 1644,
        "stat": "$400B", "stat_size": 340, "stat_y": 670,
        "line1": "Richest human ever", "l1_size": 90, "l1_y": 1140,
        "line2": "walked the Earth", "l2_size": 86, "l2_y": 1260,
        "category": "Mansa Musa",
    },
}


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else None

    if target:
        items = [(target, THUMBNAILS[target])] if target in THUMBNAILS else []
        if not items:
            print(f"❌ Unknown ID: {target}")
            return
    else:
        items = list(THUMBNAILS.items())

    print(f"\n🎨 Generating {len(items)} AI-powered thumbnails (Pollinations.ai Flux)\n")

    success = 0
    for vid_id, cfg in items:
        try:
            make_thumbnail_ai(vid_id, cfg)
            success += 1
        except Exception as e:
            print(f"  ❌ {vid_id}: {e}")
        time.sleep(1)  # polite delay between API calls

    print(f"\n✅ {success}/{len(items)} thumbnails generated")


if __name__ == "__main__":
    main()
