#!/bin/bash
set -e
cd "/Users/ar/Development/projects/FactForge/video/remotion-project"

echo "=== Rendering S01062 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01062/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01062/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01062" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01062/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01062/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01062/video.mp4" -y && echo "✓ Merge done S01062"

echo "=== Rendering S01110 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01110/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01110/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01110" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01110/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01110/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01110/video.mp4" -y && echo "✓ Merge done S01110"

echo "=== Rendering S01155 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01155/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01155/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01155" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01155/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01155/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01155/video.mp4" -y && echo "✓ Merge done S01155"

echo "=== Rendering S01183 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01183/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01183/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01183" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01183/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01183/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01183/video.mp4" -y && echo "✓ Merge done S01183"

echo "=== Rendering S01185 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01185/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01185/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01185" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01185/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01185/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01185/video.mp4" -y && echo "✓ Merge done S01185"

echo "=== Rendering S01190 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01190/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01190/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01190" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01190/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01190/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01190/video.mp4" -y && echo "✓ Merge done S01190"

echo "=== Rendering S01215 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01215/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01215/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01215" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01215/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01215/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01215/video.mp4" -y && echo "✓ Merge done S01215"

echo "=== Rendering S01224 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01224/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01224/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01224" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01224/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01224/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01224/video.mp4" -y && echo "✓ Merge done S01224"

echo "=== Rendering S01267 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01267/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01267/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01267" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01267/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01267/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01267/video.mp4" -y && echo "✓ Merge done S01267"

echo "=== Rendering S01268 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01268/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01268/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01268" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01268/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01268/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01268/video.mp4" -y && echo "✓ Merge done S01268"


echo ""
echo "✅ ALL 10 VIDEOS RENDERED AND MERGED SUCCESSFULLY"
echo "Videos ready in: /Users/ar/Development/projects/FactForge/output/"
python3 "/Users/ar/Development/projects/FactForge/scripts/batch_finalize.py"
