#!/bin/bash
set -e
cd "/Users/ar/Development/projects/FactForge/video/remotion-project"

echo "=== Rendering S00794 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S00794/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S00794/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S00794" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S00794/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S00794/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S00794/video.mp4" -y && echo "✓ Merge done S00794"

echo "=== Rendering S00925 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S00925/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S00925/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S00925" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S00925/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S00925/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S00925/video.mp4" -y && echo "✓ Merge done S00925"

echo "=== Rendering S01066 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01066/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01066/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01066" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01066/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01066/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01066/video.mp4" -y && echo "✓ Merge done S01066"

echo "=== Rendering S01080 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01080/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01080/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01080" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01080/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01080/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01080/video.mp4" -y && echo "✓ Merge done S01080"

echo "=== Rendering S01084 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01084/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01084/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01084" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01084/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01084/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01084/video.mp4" -y && echo "✓ Merge done S01084"

echo "=== Rendering S01097 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01097/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01097/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01097" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01097/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01097/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01097/video.mp4" -y && echo "✓ Merge done S01097"

echo "=== Rendering S01113 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01113/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01113/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01113" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01113/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01113/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01113/video.mp4" -y && echo "✓ Merge done S01113"

echo "=== Rendering S01128 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01128/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01128/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01128" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01128/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01128/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01128/video.mp4" -y && echo "✓ Merge done S01128"

echo "=== Rendering S01131 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01131/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01131/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01131" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01131/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01131/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01131/video.mp4" -y && echo "✓ Merge done S01131"

echo "=== Rendering S01644 ===" && ./node_modules/.bin/remotion render src/index.ts ShortVideo "/Users/ar/Development/projects/FactForge/output/S01644/video_noaudio.mp4" --props="/Users/ar/Development/projects/FactForge/output/S01644/remotion_props.json" --codec=h264 --concurrency=4 && echo "✓ Render done S01644" && ffmpeg -i "/Users/ar/Development/projects/FactForge/output/S01644/video_noaudio.mp4" -i "/Users/ar/Development/projects/FactForge/output/S01644/audio.mp3" -c:v copy -c:a aac -b:a 256k -shortest "/Users/ar/Development/projects/FactForge/output/S01644/video.mp4" -y && echo "✓ Merge done S01644"

python3 scripts/batch_finalize_2.py